=== raul-rrg/XML-DTD/XML-DTD-III/Cuentos/cuentos.dtd
<!-- Definimos la estructura del cuento -->
<!ELEMENT cuento (personajes, trama, etiqueta*, precio?)>
<!-- DEfinimos los atributos del cuento-->
<!ATTLIST cuento cod CDATA #REQUIRED
                  título CDATA #REQUIRED
                  género (infantil|fantasía|terror) #IMPLIED>

<!-- Contenedor de personajes debemos de definir que habra al mini mo uno  -->
<!ELEMENT personajes (personaje+)> 
<!-- Definimos un personaje -->
<!ELEMENT personaje (nombre, género, descripción?)>
<!-- Atributos del personaje, donde debeoos de indicar ID unico obligatorio y tipo con valor por defecto "principal" -->
<!ATTLIST personaje id ID #REQUIRED
                   tipo (principal|secundario|antagonista) "principal">

<!-- Definimos los elementos basicos que debe de tener un personaje -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT género (#PCDATA)>
<!ELEMENT descripción (#PCDATA)>

<!-- Definimos la trama del cuento -->
<!ELEMENT trama (#PCDATA)>

<!-- Definimos las etiquetas opcionales para clasificar el cuento -->
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta nombre CDATA #REQUIRED>

<!-- Definimos el precio como opcional con un atributo moneda que por defecto es "eur" -->
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA "eur">

=== raul-rrg/XML-DTD/XML-DTD-III/Cuento1/cuento2.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!--Añadimos la declarcion inicial en el que incluimos como atribito la version y el formato de codigo, esta 
siempre debe ser la primera linea del documento XML-->

<!--
Nombre: Raul Rivera Garrido
Curso: 1 º DAM
Fecha: [29/03/2025]
Cuento-2: Don Quijote
-->

<!--Definimos las ruta del DTD externo-->
<!DOCTYPE cuento SYSTEM "cuentos.dtd">

<cuento cod="F02" título="Don Quijote de la Mancha" género="fantasía">
    <personajes>
        <personaje id="Pers-1" tipo="principal">
            <nombre>Don Quijote</nombre>
            <género>M</género>
            <descripción>Un hidalgo que pierde la razon y se cree caballero andantee</descripción>
        </personaje>
        <personaje id="Person-2" tipo="secundario">
            <nombre>Sancho Panza</nombre>
            <género>M</género>
            <descripción>El fiel escudero de Don Quijote, practico y leal</descripción>
        </personaje>
    </personajes>
    <trama>Don Quijote emprende una serie de aventuras en busca de justicia, enfrentando molinos de viento y otros desafios</trama>
    <etiqueta nombre="aventura"/>
    <etiqueta nombre="caballería"/>
</cuento>

=== raul-rrg/XML-DTD/XML-DTD-III/Cuentos/cuento1.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!--Añadimos la declarcion inicial en el que incluimos como atribito la version y el formato de codigo, esta 
siempre debe ser la primera linea del documento XML-->

<!--
Nombre: Raul Rivera Garrido
Curso: 1 º DAM
Fecha: [29/03/2025]
Cuento-1: La Leyenda del Cid
-->

<!--Definimos las ruta del DTD externo-->
<!DOCTYPE cuento SYSTEM "cuentos.dtd">

<cuento cod="F01" título="La leyenda del Cid" género="fantasía">
    <personajes>
        <personaje id="Perso-1" tipo="principal">
            <nombre>Rodrigo Diaz de Vivar</nombre>
            <género>M</género>
            <descripción>Un valiente caballero castellano que luchaa por su honnor y justicia.</descripción>
        </personaje>
        <personaje id="Perso-2" tipo="secundario">
            <nombre>Doña Jimena</nombre>
            <género>F</género>
            <descripción>esposa del Cid, fiel y noble</descripción>
        </personaje>
    </personajes>
    <trama>El Cid es desterrado por el rey alfonso, pero con honor y valentia conquista tierras y se gana el respeto de todos</trama>
    <etiqueta nombre="historia"/>
    <etiqueta nombre="caballeros"/>
    <precio moneda="eur">10.99</precio>
</cuento>
