<?xml version="1.0" encoding="UTF-8"?> 
<!--Añadimos la declarcion inicial en el que incluimos como atributo la version y el formato de codigo, esta 
siempre debe ser la primera linea del documento XML-->

<!--
Nombre: Raul Rivera Garrido
Curso: 1 º DAM
Fecha: [6/04/2025]
Ejercicio-2
-->
<!DOCTYPE inventores [
   <!--Se corrigio la definición de inventores para especificar que debe de contener uno o mas inventores-->
   <!ELEMENT inventores (inventor+)>
   <!ELEMENT inventor EMPTY>
   <!ATTLIST inventor invento CDATA #REQUIRED>
   <!--Ademas se modifico el atributo inventor para que contienese CDATA y no ID ya que no en todos los casos tendremos un nombre-->
   <!ATTLIST inventor nombre CDATA #IMPLIED>
]>

<inventores>
 <inventor nombre="Robert Adler" invento="Mando a distancia"></inventor>
 <inventor nombre="Laszlo Josef Biro" invento="Bolígrafo"></inventor>
 <inventor nombre="Josephine Garis Cochran" invento="Lavaplatos"></inventor>
 <inventor invento="Fuego"></inventor>
</inventores>