<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE provincias [
<!ELEMENT provincias (provincia)*>
<!ELEMENT provincia (#PCDATA)>
<!ATTLIST provincia pueblo CDATA #REQUIRED>
]>
<provincias>
<provincia pueblo="Chinchón">Madrid</provincia>
<provincia pueblo="Chiclana de la Frontera">Cádiz</provincia>
<provincia pueblo="Cadaques">Girona</provincia>
<provincia pueblo="Consuegra">Toledo</provincia>
<provincia pueblo="San Lorenzo de El Escorial">Madrid</provincia>
</provincias>
