<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta_de_cocina [
<!ELEMENT receta_de_cocina (nombre, ingrediente*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingrediente (#PCDATA)>
]>
<receta_de_cocina>
<nombre>Cachopo</nombre>
<ingrediente>JamonSerrano</ingrediente>
<ingrediente>FileteTernera</ingrediente>
<ingrediente>Queso</ingrediente>
<ingrediente>Harina</ingrediente>
</receta_de_cocina>